version: 2.1

jobs:
  test_app:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - run:
          name: Get dependencies
          command: npm install
      - run:
          name: Run tests
          command: jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit

workflows:
  test:
    jobs:
      - test_app:
          filters:
            branches:
              only:
                - main


