version: 2.1

jobs:
  test_app:
    docker:
      - image: circleci/node:15
    #parallelism: 1
    steps:
      - checkout
      - run:
          name: Install Chrome
          command: sudo apt-get update && sudo apt-get install chromium
      - restore_cache:
          keys: 
            - v1-deps{{ checksum "package.json" }}
      - run:
          name: Get dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm run testci
      - store_test_results:
          path: ./junit.xml
      - store_artifacts:
          path: ./junit.xml

workflows:
  test:
    jobs:
      - test_app:
          filters:
            branches:
              only:
                - main
