version: 2.1

jobs:
  test_app:
    docker:
      - image: circleci/node:15
      #- selenium / standalone-chrome: 3.11.0
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Install Chrome
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
            apt install -fy google-chrome-stable_current_amd64.deb
      - run:
          name: Get dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm run test
      - store_test_results:
          path: ./junit.xml
      - store_artifacts:
          path: ./junit.xml

workflows:
  test:
    jobs:
      - test_app:
          filters:
            branches:
              only:
                - main
